builds:
- id: server
  dir: ./cmd/server
  binary: bin/webhook-server
  env:
  - CGO_ENABLED=0
dockers:
- goos: linux
  goarch: amd64
  binaries:
  - bin/webhook-server
  dockerfile: Dockerfile
  image_templates:
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:{{ .Tag }}"
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:v{{ .Major }}"
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:v{{ .Major }}.{{ .Minor }}"
