builds:
- id: server
  dir: ./cmd/server
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
dockers:
- goarch: amd64
  goos: linux
  builds:
  - server
  image_templates:
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:{{ .Tag }}"
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:v{{ .Major }}"
  - "docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server:v{{ .Major }}.{{ .Minor }}"
archives:
- format: binary