builds:
- id: server
  dir: ./cmd/server
  binary: /bin/webhook-server
  env:
  - CGO_ENABLED=0
dockers:
- builds:
  - server
  binaries:
  - /bin/webhook-server
  image_templates:
  - docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server
