builds:
- name: server
  dir: ./cmd/server
  binary: /bin/webhook-server
  env:
  - CGO_ENABLED=0
release:
  github:
    owner: goci-io
    name: kubernetes-deployment-webhook
dockers:
- builds:
  - server
  binaries:
  - /bin/webhook-server
  image_templates:
  - docker.pkg.github.com/goci-io/kubernetes-deployment-webhook/server
