name: goreleaser
on:
  push:
    branches:
    - master
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Login to Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login docker.pkg.github.com -u docker --password-stdin
      - name: Build Binary
        run: make image/server
      - name: Build Image
        run: make image/docker
      - name: Release Latest
        run: make image/docker/release
      - name: New Release
        if: startsWith(github.ref, 'refs/tags/')
        run: make image/docker/release GIT_REF={{ github.ref }}
