name: Validate
on: 
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - master
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Go Tests
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make tests
